### ISSUE TITLE
能否考虑新的ip库

### ISSUE THREAD

**Issue by mengxinz** [ChanthMiao/China-IPv4-List#3]
https://github.com/pmkol/easymosdns/tree/rules 这个库准确性应该不错的，但是ipv4和ipv6数据他没有分开你能不能做一份独立的v4和v6数据

**Comment by ChanthMiao** [comment]
我没太明白你的意思

**Comment by mengxinz** [comment]
> 我没太明白你的意思

我意思这个多数据库合并去重好像更准确，但是ipv4和ipv6数据没有向你一样分开我又不会，你能不能搞一个我直接下载你的
